#!/usr/bin/env bash
# This script displays its own PID
PIDF=/var/run/my_process.pid
FILE=./manage_my_process

if [ "$1" == "start" ]; then
    $FILE &
    echo $! > $PIDF
    echo manage_my_process started
elif [ "$1" == "stop" ]; then
    pid_file="$PIDF"
    pid=$(cat "$pid_file")
    kill -9 "$pid"
    rm "$pid_file"
    echo manage_my_process stopped
elif [ "$1" = "restart" ]; then
    pid_file="$PIDF"
    pid=$(cat "$pid_file")
    kill -9 "$pid"
    rm "$pid_file"
    $FILE &
    echo $! > $PIDF
    echo manage_my_process restarted
else 
    echo "Usage: manage_my_process {start|stop|restart}"
fi
