#!/usr/bin/env bash
# This script is displaying the string "Best School" 10 times
k=1
while [ $k -le  20 ]
do
case $k in
4) echo -e $k"\n"bad luck from China;;
9) echo -e $k"\n"bad luck from Japan;;
17) echo -e $k"\n"bad luck from Italy;;
*) echo $k
esac
k=$((k+1))
done
