#!/usr/bin/env bash
# This script is displaying the string "Best School" 10 times
k=0
while [ $k -le  12 ]
do
echo Hour: $k
j=1
    while [ $j -le 59 ] 
    do
        echo $j
        j=$((j+1))
    done
k=$((k+1))
done
