#!/usr/bin/env bash
# This scripts modifies th IP address of the local host and that of facebook.com

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
